export enum CondizioniOpera {
	RESTAURO_NECESSARIO = "RESTAURO_NECESSARIO",
	DISCRETE_CONDIZIONI = "DISCRETE_CONDIZIONI",
	BUONE_CONDIZIONI = "BUONE_CONDIZIONI",
	OTTIME_CONDIZIONI = "OTTIME_CONDIZIONI"
}
