export enum TecnicaOpera {

	ACQUERELLO = "ACQUERELLO",
	ACRILICO = "ACRILICO",
  OLIO = "OLIO",
  PASTELLO = "PASTELLO",
  TEMPERA = "TEMPERA",
  DIGITALE = "DIGITALE",
  CALOTIPIA = "CALOTIPIA",
	INCISIONE = "INCISIONE",
  TECNICA_MISTA = "TECNICA_MISTA",
	ALTRO = "ALTRO"

}
